### ISSUE TITLE
About backbone frozen training

### ISSUE THREAD

**Issue by ZiYuTou** [hustvl/WeakCLIP#2]
Thank you for your outstanding contribution! When reading your code, I found that you froze the backbone (i.e. CLIPVisionTransformer) by setting its learning rate to zero in the settings. However, in the backbone, in addition to the original part of the CLIP, there are also some newly defined fpn layers, including some untrained ConvTranspose2d layers. Do these layers not need to be trained?

**Comment by lh-zhu** [comment]
Hi, ZiYuTou!
The current version is the intermediate version code of WeakCLIP. In the final version, we separate the FPN from the visual backbone to ensure the parameter updating. We are cleaning the final version of the code and commit it to GitHub soon.

**Comment by ZiYuTou** [comment]
OK, Thanks for your reply!
